sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: eRlNi2sguOCKJ1opo7RZFPBSARtXGdVKQZc2k8klWPD/lwIRxBNuvd3TXnEKFQf9P+MFpWoaOF9pP8t6ocbU3pAXjFk0cHowK5Rgu/50om063QKEli+vfv6maz4cekYvwOLjqSDRNVU1s6UDsHyMHcD/NvoRzsBbFF8yU4hKBz3lR8QFXgZ7klUl28qtsWJctpRLKg+hD4UqwNeCQ3ztbOhq/n+yf+dpxRmL0IREFaKirtyV5kygJnH6doBEkY8BOth98nlCsmyXFHSKfP+Q+lW+NmVSNWeAmDT4CX+WhFyM7fPPVv6jalOhaa2hGA6Pn22FLFEFahKug5RlYEcDfgxA87PKGr3Q/uTkfq+V/CHt4q8+FKyh96YtpZNCrDEXjiMF8L40IoXEIkoH+rMlHadj0ncLC3wcgnAt6mRRAO/fkxFSnBnpIzfHR4ipljqJQP7thFmsJiMaKWeM+LW/eTgMPVxc3Ym626vTPhMNtUfpb6D14h74WJKjwmoEqaAjAiRsP0/YDpx4Cc6DyTa1c4HkM12lWZLDzzfi0WQpfrdHRMR/RSbDcGI/fdzxsFdh3E2W3S7KBUyMMUSKyyMBaTzCb7HrI9xTO6DV32XIw3s7yL3SONOahC7f2qw09x/0PGuDSYOOPFuOcLVOLsHWuX8yh7nuBVSjVMdZQnNK/60=
  on: heroku_production
  app: probot-greciamy
